# Generated by Django 5.2.3 on 2025-08-08 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CFOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True, verbose_name='Código CFOP')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'CFOP',
                'verbose_name_plural': 'CFOPs',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='NCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True, verbose_name='Código NCM')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'NCM',
                'verbose_name_plural': 'NCMs',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=50, unique=True, verbose_name='Código do Produto')),
                ('unidade', models.CharField(choices=[('BDJ', 'Bandeja'), ('VASO', 'Vaso'), ('CUIA', 'Cuia'), ('MUDAS', 'Mudas'), ('KG', 'Quilograma'), ('G', 'Grama'), ('PC', 'Pacote'), ('UN', 'Unidade')], max_length=10, verbose_name='Unidade de Medida')),
                ('qtd_unid', models.CharField(choices=[('1UN', '1 Unidade'), ('15UN', '15 Unidades'), ('128UN', '128 Unidades'), ('30UN', '30 Unidades')], max_length=10, verbose_name='Quantidade por Unidade')),
                ('tipo', models.CharField(choices=[('Tempero', 'Tempero'), ('Hibridos', 'Híbridos'), ('Cacto', 'Cacto'), ('Flores', 'Flores'), ('Frutas', 'Frutas'), ('Plantas Ornamentais', 'Plantas Ornamentais'), ('Arvores Frutiferas', 'Árvores Frutíferas'), ('Arvores Nativas', 'Árvores Nativas'), ('Hortalicas', 'Hortaliças'), ('Suculentas', 'Suculentas'), ('Vasos', 'Vasos'), ('Substratos', 'Substratos'), ('Adubos', 'Adubos'), ('Ferramentas', 'Ferramentas'), ('Outros', 'Outros')], max_length=50, verbose_name='Tipo de Produto')),
                ('variedade', models.CharField(max_length=100, verbose_name='Variedade')),
                ('especie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Espécie')),
                ('cod_especie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código da Espécie')),
                ('cultivar_info', models.TextField(blank=True, null=True, verbose_name='Informações sobre Cultivar')),
                ('descricao_catalogo', models.TextField(blank=True, help_text='Descrição mais completa do produto para exibição no catálogo online.', null=True, verbose_name='Descrição Detalhada para Catálogo')),
                ('estoque', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estoque')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Com Estoque', 'Com Estoque'), ('Sem Estoque', 'Sem Estoque')], default='Ativo', max_length=20, verbose_name='Status')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos_imagens/', verbose_name='Imagem do Produto')),
                ('data_cadastro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de Cadastro')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('cfop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.cfop', verbose_name='CFOP')),
                ('ncm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.ncm', verbose_name='NCM')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['variedade'],
            },
        ),
    ]
