# Generated by Django 5.2.3 on 2025-08-08 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, help_text='Gerado automaticamente: Código do Produto + Data de Semeadura (DDMMYY).', max_length=50, unique=True, verbose_name='Código de Identificação Interna do Lote')),
                ('data_semeadura', models.DateField(verbose_name='Data de Semeadura')),
                ('quantidade', models.PositiveIntegerField(default=0, help_text='Quantidade disponível neste lote (unidades).', verbose_name='Quantidade em Unidades')),
                ('preco_unitario', models.DecimalField(decimal_places=2, editable=False, help_text='Copiado do preço do Produto ao salvar.', max_digits=10, verbose_name='Preço Unitário')),
                ('observacoes', models.TextField(blank=True, help_text='Informações adicionais sobre este lote.', null=True, verbose_name='Observações do Lote')),
                ('produto', models.ForeignKey(help_text='Produto ao qual este lote pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-data_semeadura', 'codigo'],
            },
        ),
    ]
