# Generated by Django 5.2.3 on 2025-08-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_fornecedores', '0002_cliente_inscricao_estadual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_unico',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Único'),
        ),
    ]
