# Generated by Django 5.2.3 on 2025-08-12 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotes', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Lote')),
                ('variedade_produto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Variedade do Produto')),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('nome_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Cliente')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lotes.lote')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
