# Generated by Django 5.2.3 on 2025-08-08 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Máquina')),
                ('tipo', models.CharField(choices=[('TRATOR', 'Trator'), ('ROÇADEIRA', 'Roçadeira'), ('PULVERIZADOR', 'Pulverizador'), ('GERADOR', 'Gerador'), ('CULTIVADOR', 'Cultivador'), ('OUTRO', 'Outro')], default='OUTRO', max_length=50, verbose_name='Tipo de Máquina')),
                ('identificacao', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Identificação/Série')),
                ('ano_fabricacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Fabricação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Veículo')),
                ('placa', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Placa')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('ano_fabricacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Fabricação')),
                ('tipo_combustivel', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('ETANOL', 'Etanol'), ('DIESEL', 'Diesel'), ('FLEX', 'Flex'), ('ELETRICO', 'Elétrico'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Tipo de Combustível')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_manutencao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Manutenção')),
                ('tipo_manutencao', models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva'), ('LUBRIFICACAO', 'Lubrificação'), ('OUTRO', 'Outro')], default='PREVENTIVA', max_length=50, verbose_name='Tipo de Manutenção')),
                ('descricao', models.TextField(verbose_name='Descrição da Manutenção')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo (R$)')),
                ('realizada_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Realizada por')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes', to='veiculos_maquinas.maquina', verbose_name='Máquina')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes', to='veiculos_maquinas.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-data_manutencao'],
            },
        ),
    ]
